DROP TABLE CARD
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CARD;

CREATE TABLE CARD (
    CARDSEQ NUMBER CONSTRAINT PK_CARD_01 PRIMARY KEY,
    CARDTITLE VARCHAR2(200),
    CARDTEXT VARCHAR2(4000),
    CARDSTART DATE,
    CARDEND DATE,
    BOOKNUM NUMBER,
    CONSTRAINT FK_CARD_01 FOREIGN KEY(BOOKNUM) 
    REFERENCES BOOK(BOOKNUM),
    CLUBSEQ NUMBER,
    CONSTRAINT FK_CARD_02 FOREIGN KEY(CLUBSEQ) 
    REFERENCES CLUB(CLUBSEQ)
);

CREATE SEQUENCE SEQ_CARD
START WITH 5000
INCREMENT BY 1;

SELECT CARDSEQ, CARDTITLE, CARDTEXT, CARDSTART, CARDEND, B.BOOKIMAGE, C.CLUBSEQ 
FROM CARD C, BOOK B  
WHERE C.BOOKNUM=B.BOOKNUM AND CLUBSEQ=1000
SELECT * FROM CARD;

SELECT C.CARDSEQ, C.CARDTITLE, C.CARDTEXT, C.CARDSTART, C.CARDEND, B.BOOKIMAGE, C.CLUBSEQ 
				 FROM CARD C, BOOK B 
				 WHERE C.BOOKNUM=B.BOOKNUM AND C.CARDSEQ=5007 


-- 같은 CLUBSEQ 번호에 같은 BOOKNUM가 INSERT 되면 안된다. 즉) 클럽하나에 같은 책이 등록되는 것을 방지해야한다. 

INSERT INTO CARD (CARDSEQ, CARDTITLE, CARDTEXT, CARDSTART, CARDEND, BOOKNUM, CLUBSEQ)
VALUES (SEQ_CARD.NEXTVAL, '1', '안녕', SYSDATE, SYSDATE, 10000, 1000);

INSERT INTO CARD (CARDSEQ, CARDTITLE, CARDTEXT, CARDSTART, CARDEND, BOOKNUM, CLUBSEQ)
VALUES (SEQ_CARD.NEXTVAL, '2', '잘가', SYSDATE, SYSDATE, 10000, 1001);

INSERT INTO CARD (CARDSEQ, CARDTITLE, CARDTEXT, CARDSTART, CARDEND, BOOKNUM, CLUBSEQ)
VALUES (SEQ_CARD.NEXTVAL, '3', '잘자', SYSDATE, SYSDATE, 10001, 1000 );

INSERT INTO CARD (CARDSEQ, CARDTITLE, CARDTEXT, CARDSTART, CARDEND, BOOKNUM, CLUBSEQ)
VALUES (SEQ_CARD.NEXTVAL, '4', '안녕', SYSDATE, SYSDATE, 10002, 1000 );

INSERT INTO CARD (CARDSEQ, CARDTITLE, CARDTEXT, CARDSTART, CARDEND, BOOKNUM, CLUBSEQ)
VALUES (SEQ_CARD.NEXTVAL, '5', '잘가', SYSDATE, SYSDATE, 10003, 1001);

INSERT INTO CARD (CARDSEQ, CARDTITLE, CARDTEXT, CARDSTART, CARDEND, BOOKNUM, CLUBSEQ)
VALUES (SEQ_CARD.NEXTVAL, '6', '잘자', SYSDATE, SYSDATE, 10003, 1000 );

INSERT INTO CARD (CARDSEQ, CARDTITLE, CARDTEXT, CARDSTART, CARDEND, BOOKNUM, CLUBSEQ)
VALUES (SEQ_CARD.NEXTVAL, '7', '안녕', SYSDATE, SYSDATE, 10002, 1001 );

INSERT INTO CARD (CARDSEQ, CARDTITLE, CARDTEXT, CARDSTART, CARDEND, BOOKNUM, CLUBSEQ)
VALUES (SEQ_CARD.NEXTVAL, '8', '잘가', SYSDATE, SYSDATE, 10005, 1001);

INSERT INTO CARD (CARDSEQ, CARDTITLE, CARDTEXT, CARDSTART, CARDEND, BOOKNUM, CLUBSEQ)
VALUES (SEQ_CARD.NEXTVAL, '9', '잘자', SYSDATE, SYSDATE, 10004, 1000 );

SELECT * FROM CARD;

SELECT CA.CARDSEQ, TA.TALKSEQ, TA.TALKCONTENT, MB.USERID
FROM CARD CA, TALK TA, MEMBERS MB
WHERE CA.CARDSEQ = TA.CARDSEQ
	AND TA.MEMBERNUM = MB.MEMBERNUM
		AND CA.CARDSEQ = 5000;
