DROP TABLE CLUB
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CLUB;

CREATE TABLE CLUB (
    CLUBSEQ NUMBER CONSTRAINT PK_CLUB_01 PRIMARY KEY,
    CLUBTITLE VARCHAR2(200),
    CLUBTEXT VARCHAR2(4000),
    CLUBDATE DATE,
    MEMBERNUM NUMBER,
    CONSTRAINT FK_CLUB_01 FOREIGN KEY(MEMBERNUM) 
    REFERENCES MEMBERS(MEMBERNUM),
    CLUBIMAGE VARCHAR2(50)
);

CREATE SEQUENCE SEQ_CLUB
START WITH 1000
INCREMENT BY 1;

SELECT * FROM CLUB C;

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '달이를 사랑하는 사람들의 모임', '달이 사랑해용', SYSDATE, 100, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '은지를 사랑하는 사람들의 모임', '드루와', SYSDATE, 101, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '연우를 사랑하는 사람들의 모임', '사랑스런 연우 관련', SYSDATE, 102, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '민선이를 사랑하는 사람들의 모임', '사랑스런 민선언니 관련', SYSDATE, 103, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '안근이를 사랑하는 사람들의 모임', '조장 관련', SYSDATE, 104, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '민이를 사랑하는 사람들의 모임', '허민관련', SYSDATE, 110, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '토끼를 사랑하는 사람들의 모임', '토끼는 귀여워 깡총깡총', SYSDATE, 111, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '바보를 사랑하는 사람들의 모임', '바보도 사람이다', SYSDATE, 112, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '철학를 사랑하는 사람들의 모임', '철학은 즐거워', SYSDATE, 113, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '영어를 사랑하는 사람들의 모임', '영어회화를 연습하는 사람들입니다.', SYSDATE, 114, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '성경를 사랑하는 사람들의 모임', '신천지 아닙니다 반갑습니다. ', SYSDATE, 115, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '바퀴벌레를 사랑하는 사람들의 모임', '벌레 사랑해 관련', SYSDATE, 122, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '날벌레를 사랑하는 사람들의 모임', '놀러오세요', SYSDATE, 123, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '파리를 사랑하는 사람들의 모임', '놀자야야야야야', SYSDATE, 124, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '커피를 사랑하는 사람들의 모임', '즐거운 모임이다', SYSDATE, 125, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '청포도를 사랑하는 사람들의 모임', '청포도 관련 입니다.', SYSDATE, 126, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, '아아메를 사랑하는 사람들의 모임', '아아메 관련', SYSDATE, 108, '24353');


SELECT CLUBSEQ, C.MEMBERNUM FROM CLUBLINK C, MEMBERS M 
WHERE C.MEMBERNUM=M.MEMBERNUM AND 
(CLUBSEQ=1016 AND C.MEMBERNUM=108) OR (CLUBSEQ=1016 AND M.CLUBMASTER=1)

SELECT C.CLUBSEQ, C.CLUBTITLE, A.BOOKNUM FROM CARD A, CLUB C 
WHERE A.CLUBSEQ=C.CLUBSEQ AND A.BOOKNUM=?

(SELECT ROW_NUMBER()OVER(PARTITION BY CLUBSEQ ORDER BY BOOKNUM) AS RNUM,
		COUNT(*)OVER(PARTITION BY CLUBSEQ),
		CLUBSEQ, CLUBTI 
FROM CARD A, CLUB C 
WHERE A.CLUBSEQ=C.CLUBSEQ AND A.BOOKNUM=? ) 

-- 클럽장
SELECT C.CLUBSEQ, C.CLUBTITLE, M.MEMBERNUM, M.USERID
FROM CLUB C, MEMBERS M
WHERE C.MEMBERNUM = M.MEMBERNUM;

-- 클럽에 가입한 멤버들
SELECT C.CLUBSEQ, C.CLUBTITLE, M.MEMBERNUM, M.USERID
FROM CLUB C, MEMBERS M, CLUBLINK CL
WHERE C.CLUBSEQ = CL.CLUBSEQ
		AND M.MEMBERNUM = CL.MEMBERNUM;

SELECT *
FROM CLUB C;
		
SELECT MA.MEMBERNUM, CL.CLUBSEQ, CA.BOOKNUM, CA.CARDSEQ
FROM CLUB CL, CARD CA, MEMBERS MA
WHERE CL.CLUBSEQ = CA.CLUBSEQ
		AND CL.MEMBERNUM = MA.MEMBERNUM;
		
SELECT RNUM, CL.CLUBSEQ, CL.CLUBTITLE, CL.CLUBIMAGE, CL.CLUBDATE
   FROM ( SELECT ROW_NUMBER()OVER( COUNT(CA.CARDSEQ)OVER(PARTITION BY CA.CLUBSEQ ORDER BY CA.CARDSEQ DESC TA.TALKSEQ DESC) ) AS RNUM, CL.CLUBSEQ, CL.CLUBTITLE, CL.CLUBIMAGE, CL.CLUBDATE 
      	FROM CARD CA, TALK TA, CLUB CL
     	 WHERE CA.CARDSEQ = TA.CARDSEQ
            AND CL.CLUBSEQ = CA.CLUBSEQ );

SELECT C.CLUBSEQ, SUM(SUMTALK), C.BOOKNUM
FROM CARD C, (SELECT CARDSEQ, COUNT(*) AS SUMTALK
    			FROM TALK
    			GROUP BY CARDSEQ) S
WHERE C.CARDSEQ = S.CARDSEQ AND BOOKNUM=?
GROUP BY CLUBSEQ
ORDER BY SUM(SUMTALK) DESC
            
 

SELECT RNUM, CL.CLUBSEQ, CL.CLUBTITLE, CL.CLUBIMAGE, CL.CLUBDATE
FROM (SELECT ROW_NUMBER()OVER(PARTITION BY CL.CLUBSEQ ORDER BY CA.CARDSEQ DESC) AS RNUM, CL.CLUBSEQ, CL.CLUBTITLE, CL.CLUBIMAGE, CL.CLUBDATE 
		FROM CARD CA, CLUB CL, TALK TA
     	 WHERE CL.CLUBSEQ = CA.CLUBSEQ 
     	 ) 

SELECT CB.CLUBSEQ, CL.MEMBERNUM, MB.USERID, MB.
FROM CLUB CB, CLUBLINK CL, MEMBERS MB
WHERE CB.CLUBSEQ = CL.CLUBSEQ
	AND CL.MEMBERNUM = MB.MEMBERNUM
		AND CB.CLUBSEQ = 1001;

SELECT RNUM, CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE 
FROM (SELECT ROW_NUMBER()OVER(ORDER BY CLUBSEQ DESC) AS RNUM, 
					CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE 
					FROM CLUB
					WHERE CLUBTITLE LIKE '%A%'  
				    ORDER BY CLUBSEQ DESC) 
WHERE RNUM >= 1 AND RNUM <= 16;

SELECT * FROM CLUB;

SELECT COUNT(*)
FROM CLUBLINK
WHERE MEMBERNUM = 100 



 SELECT CLUBSEQS, CLUBTITLE, CLUBTEXT, CLUBIMAGE, RNUM 
 FROM (SELECT ROW_NUMBER()OVER(ORDER BY CL.CLUBSEQ DESC) AS RNUM, CL.CLUBSEQ AS CLUBSEQS, CLUBTITLE, CLUBTEXT, CLUBIMAGE 
        FROM CLUBLINK CL, CLUB C
        WHERE CL.CLUBSEQ = C.CLUBSEQ 
        AND CL.MEMBERNUM = 100 )
  WHERE RNUM >= 1 AND RNUM <= 3 ;
  
SELECT CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, M.USERID, CLUBIMAGE,
FROM CLUB C, MEMBERS M
WHERE M.MEMBERNUM = C.MEMBERNUM AND CLUBSEQ=1016

SELECT CLUBSEQ, MEMBERNUM FROM CLUBLINK  WHERE CLUBSEQ=1016 AND MEMBERNUM=127 
				
SELECT COUNT(*)		
FROM CLUB
WHERE MEMBERNUM=102

SELECT CLUBSEQS, CLUBTITLE, CLUBTEXT, CLUBIMAGE, RNUM
FROM (SELECT ROW_NUMBER()OVER(ORDER BY CL.CLUBSEQ DESC) AS RNUM, CL.CLUBSEQ AS CLUBSEQS, CLUBTITLE, CLUBTEXT, CLUBIMAGE 
        FROM CLUBLINK CL, CLUB C
        WHERE CL.CLUBSEQ = C.CLUBSEQ )
  WHERE RNUM >= 1 AND RNUM <= 5 ;

SELECT CLUBSEQS, CLUBTITLE, CLUBTEXT, CLUBIMAGE, RNUM, STARTDATE, ENDDATE
FROM (SELECT ROW_NUMBER()OVER(PARTITION BY SUBSTR(SCHSTART, 1, 8)ORDER BY SCHSTART ASC) AS RNUM,
			CLUBSEQS, CLUBTITLE, CLUBTEXT, CLUBIMAGE
			ROW_NUMBER()OVER(PARTITION BY SCHSTART ORDER BY SCHSTART ASC) AS STARTDATE,
			ROW_NUMBER()OVER(PARTITION BY SCHEND ORDER BY SCHEND ASC) AS ENDDATE
			
			FROM SCHEDULE
			WHERE MEMBERNUM=104 AND SUBSTR(SCHSTART, 1, 7)='2021/04' OR SUBSTR(SCHEND, 1, 7)='2021/04') SC, BOOK BO
WHERE SC.BOOKNUM = BO.BOOKNUM
	AND STARTDATE <= 1
		AND ENDDATE <= 1;

SELECT ROW_NUMBER()OVER(ORDER BY SUM DESC), CB.CLUBSEQ
FROM CLUB CB, (SELECT CLUBSEQ, COUNT(*) AS SUM
      FROM CLUBLINK
      GROUP BY CLUBSEQ) CL
WHERE CB.CLUBSEQ = CL.CLUBSEQ;

SELECT CB.CLUBSEQ, CB.CLUBTITLE, CB.CLUBTEXT, CB.CLUBDATE, CB.MEMBERNUM, CB.CLUBIMAGE, RNUM, SUM
			FROM CLUB CB, (SELECT ROW_NUMBER()OVER(ORDER BY CL.SUM DESC) AS RNUM , CL.CLUBSEQ
				FROM  (SELECT CLUBSEQ, COUNT(*) AS SUM FROM CLUBLINK GROUP BY CLUBSEQ) CL) CT
WHERE CB.CLUBSEQ = CT.CLUBSEQ
AND RNUM BETWEEN 1 AND 4

SELECT CB.CLUBSEQ, CB.CLUBTITLE, CB.CLUBTEXT, CB.CLUBDATE, CB.MEMBERNUM, CB.CLUBIMAGE, MB.USERID,
ROW_NUMBER()OVER(ORDER BY CCL.SUM DESC) AS RNUM 
FROM CLUB CB, MEMBERS MB, (SELECT  CL.CLUBSEQ, CL.MEMBERNUM, SU.SUM
	 						FROM CLUBLINK CL, (SELECT CLUBSEQ, COUNT(*) AS SUM
	 										FROM CLUBLINK
	 										GROUP BY CLUBSEQ ) SU
	 						WHERE CL.CLUBSEQ = SU.CLUBSEQ
	 						) CCL
WHERE ( CB.CLUBSEQ = CCL.CLUBSEQ
	OR CB.MEMBERNUM = MB.MEMBERNUM )
		AND CCL.MEMBERNUM = CB.MEMBERNUM
		

SELECT CL.CLUBSEQ, CL.CLUBTITLE, AL.TALKSUM 
        FROM CLUB CL, (SELECT C.CARDSEQ, T.TALKSUM, C.BOOKNUM, C.CLUBSEQ 
            FROM CARD C, (SELECT CARDSEQ, COUNT(*) AS TALKSUM FROM TALK GROUP BY CARDSEQ) T 
           	 	WHERE C.CARDSEQ=T.CARDSEQ) AL 
            	WHERE CL.CLUBSEQ = AL.CLUBSEQ AND AL.BOOKNUM=?
            	
            	
SELECT CB.CLUBSEQ, CB.CLUBTITLE, CB.CLUBTEXT, CB.CLUBDATE, CB.MEMBERNUM, CB.CLUBIMAGE, SUM,
ROW_NUMBER()OVER(ORDER BY SUM DESC) AS RNUM
FROM CLUB CB, (SELECT CLUBSEQ, COUNT(*) AS SUM
FROM CLUBLINK
GROUP BY CLUBSEQ) CL
WHERE CB.CLUBSEQ = CL.CLUBSEQ
