DROP TABLE MEMBERS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_MEMBERS;

CREATE TABLE MEMBERS (
    MEMBERNUM NUMBER CONSTRAINT PK_MEMBERS_01 PRIMARY KEY,
    USERID VARCHAR2(20) NOT NULL,
    PWD VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    GENDER NUMBER,
    PHONE VARCHAR2(50),
    BIRTH VARCHAR2(50),
    ACTIVITY NUMBER,
    AUTH NUMBER NOT NULL,
    CLUBMASTER NUMBER NOT NULL, 	--클럽 마스터인지 유뮤
    USERIMAGE VARCHAR2(50) NOT NULL
);

--1:man 2:woman
--0:manager 3:user
--1:master 3:user

CREATE SEQUENCE SEQ_MEMBERS
START WITH 100
INCREMENT BY 1;

SELECT * FROM MEMBERS


SELECT MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, AUTH, CLUBMASTER, RNUM
FROM (SELECT ROW_NUMBER()OVER(ORDER BY ACTIVITY DESC) AS RNUM, MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, AUTH, CLUBMASTER
	  FROM MEMBERS)
WHERE RNUM BETWEEN 1 AND 5;

INSERT INTO MEMBERS (MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, AUTH, CLUBMASTER, USERIMAGE)
VALUES(SEQ_MEMBERS.NEXTVAL, 'admin', 'aaa', 'A@naver.com', 0, '0100000124', '2001/10/27', 0, 0, 0, 0);

INSERT INTO MEMBERS (MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, AUTH, CLUBMASTER)
VALUES(SEQ_MEMBERS.NEXTVAL, 'SC', 'glkfd', 'SV@naver.com', 1, '010004855', '1992/10/17', 23, 3, 0);

INSERT INTO MEMBERS (MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, AUTH, CLUBMASTER)
VALUES(SEQ_MEMBERS.NEXTVAL, 'WEV', 'efw', 'WEG@naver.com', 1, '01000514', '1995/02/25', 44, 3, 0);

INSERT INTO MEMBERS (MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, AUTH, CLUBMASTER)
VALUES(SEQ_MEMBERS.NEXTVAL, 'EWT', 'bbb', 'ERHA@naver.com', 0, '010545646', '1994/05/10', 62, 3, 0);

INSERT INTO MEMBERS (MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, AUTH, CLUBMASTER)
VALUES(SEQ_MEMBERS.NEXTVAL, 'ERE', 'ccc', 'ra@naver.com', 0, '01000443456', '1980/08/01', 43, 3, 0);

INSERT INTO MEMBERS (MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, AUTH, CLUBMASTER)
VALUES(SEQ_MEMBERS.NEXTVAL, 'ERE', 'ddd', 'fd@naver.com', 0, '01000334456', '1980/08/02', 44, 3, 0);

INSERT INTO MEMBERS (MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, AUTH, CLUBMASTER)
VALUES(SEQ_MEMBERS.NEXTVAL, 'ERE', 'eee', 'gr@naver.com', 0, '01000463456', '1980/08/03', 45, 3, 0);

INSERT INTO MEMBERS (MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, AUTH, CLUBMASTER)
VALUES(SEQ_MEMBERS.NEXTVAL, 'ERE', 'fff', 'h@naver.com', 0, '01000465456', '1980/08/04', 46, 3, 0);

INSERT INTO MEMBERS (MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, AUTH, CLUBMASTER)
VALUES(SEQ_MEMBERS.NEXTVAL, 'ERE', 'ggg', 'w@naver.com', 0, '01000468456', '1980/08/05', 47, 3, 1);

INSERT INTO MEMBERS (MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, AUTH, CLUBMASTER)
VALUES(SEQ_MEMBERS.NEXTVAL, 'ERE', 'ggg', 'w@naver.com', 0, '01000468456', '1980/08/05', 47, 3, 1);

SELECT MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, NVL(ACTIVITY, 0), AUTH, CLUBMASTER, USERIMAGE
FROM (SELECT ROW_NUMBER()OVER(ORDER BY NVL(ACTIVITY, 0) DESC) AS RNUM, MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, 0, AUTH, CLUBMASTER, USERIMAGE
		FROM MEMBERS)
WHERE RNUM BETWEEN 1 AND 4