DROP TABLE REVIEW
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_REVIEW;

CREATE TABLE REVIEW (
    REVSEQ NUMBER CONSTRAINT PK_REVIEW_01 PRIMARY KEY,
    REVCONTENT VARCHAR2(4000),
    REVDATE DATE,
    RATING NUMBER,
    BOOKNUM NUMBER,
    CONSTRAINT FK_REVIEW_01 FOREIGN KEY(BOOKNUM) 
    REFERENCES BOOK(BOOKNUM),
    MEMBERNUM NUMBER,
    CONSTRAINT FK_REVIEW_02 FOREIGN KEY(MEMBERNUM) 
    REFERENCES MEMBERS(MEMBERNUM)
   );

CREATE SEQUENCE SEQ_REVIEW
START WITH 1
INCREMENT BY 1;

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 4.5, 10003,  100);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 3.5, 10003,  102);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 2.5, 10003,  104);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 3.7, 10003,  111);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 2.8, 10003,  112);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 4.2, 10003,  112);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 1.5, 10003,  114);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 1.8, 10003,  103);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 2.5, 10003,  100);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 5, 10003,  100);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 4.5, 10003,  100);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 3.6, 10003,  100);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 3.7, 10003,  100);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 3.8, 10003,  100);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 3.9, 10003,  100);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 4.0, 10003,  100);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 4.1, 10003,  100);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 3.0, 10003,  100);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 3.1, 10003,  100);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 4.2, 10003,  100);

INSERT INTO REVIEW(REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUM)
VALUES(SEQ_REVIEW.NEXTVAL, '댓글 내용입니다.뭐라 어쩌구 저쩌구', SYSDATE, 4.3, 10003,  100);

SELECT * FROM REVIEW

SELECT REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, MEMBERNUMER, USERID, RNUM
FROM(SELECT REVSEQ, REVCONTENT, REVDATE, RATING, BOOKNUM, M.MEMBERNUM AS MEMBERNUMER, USERID, ROW_NUMBER()OVER(ORDER BY RATING DESC, REVSEQ DESC) AS RNUM
	FROM MEMBERS M, REVIEW R 
	WHERE M.MEMBERNUM = R.MEMBERNUM
		AND BOOKNUM = 10003 
	ORDER BY RATING DESC, REVSEQ DESC) 
WHERE RNUM BETWEEN 1 AND 5

SELECT * FROM REVIEW;

