DROP TABLE TALK
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_TALK;

CREATE TABLE TALK(
    TALKSEQ NUMBER CONSTRAINT PK_TALK_01 PRIMARY KEY,
    TALKCONTENT VARCHAR2(4000),
    TALKDATE DATE,
    MEMBERNUM NUMBER,
    CONSTRAINT FK_TALK_01 FOREIGN KEY(MEMBERNUM) 
    REFERENCES MEMBERS(MEMBERNUM),
    CARDSEQ NUMBER,
    CONSTRAINT FK_TALK_02 FOREIGN KEY(CARDSEQ) 
    REFERENCES CARD(CARDSEQ)
);

CREATE SEQUENCE SEQ_TALK
START WITH 1
INCREMENT BY 1;

INSERT INTO TALK (TALKSEQ, TALKCONTENT, TALKDATE, MEMBERNUM, CARDSEQ)
VALUES (SEQ_TALK.NEXTVAL, '안녕하신가?', SYSDATE, 100, 5006);

INSERT INTO TALK (TALKSEQ, TALKCONTENT, TALKDATE, MEMBERNUM, CARDSEQ)
VALUES (SEQ_TALK.NEXTVAL, '안녕하신가?', SYSDATE, 100, 5008);

INSERT INTO TALK (TALKSEQ, TALKCONTENT, TALKDATE, MEMBERNUM, CARDSEQ)
VALUES (SEQ_TALK.NEXTVAL, '안녕하신가?', SYSDATE, 100, 5008);

INSERT INTO TALK (TALKSEQ, TALKCONTENT, TALKDATE, MEMBERNUM, CARDSEQ)
VALUES (SEQ_TALK.NEXTVAL, '안녕하신가?', SYSDATE, 100, 5006);

INSERT INTO TALK (TALKSEQ, TALKCONTENT, TALKDATE, MEMBERNUM, CARDSEQ)
VALUES (SEQ_TALK.NEXTVAL, '안녕하신가?', SYSDATE, 100, 5006);

INSERT INTO TALK (TALKSEQ, TALKCONTENT, TALKDATE, MEMBERNUM, CARDSEQ)
VALUES (SEQ_TALK.NEXTVAL, '안녕하신가?', SYSDATE, 100, 5014);



INSERT INTO TALK (TALKSEQ, TALKCONTENT, TALKDATE, MEMBERNUM, CARDSEQ )
VALUES (SEQ_TALK.NEXTVAL, '안녕하신가?', SYSDATE, 101, 5000);

INSERT INTO TALK (TALKSEQ, TALKCONTENT, TALKDATE, MEMBERNUM, CARDSEQ )
VALUES (SEQ_TALK.NEXTVAL, '안녕하신가?', SYSDATE, 101, 5000);

INSERT INTO TALK (TALKSEQ, TALKCONTENT, TALKDATE, MEMBERNUM, CARDSEQ )
VALUES (SEQ_TALK.NEXTVAL, '안녕하신가?', SYSDATE, 101, 5000);

INSERT INTO TALK (TALKSEQ, TALKCONTENT, TALKDATE, MEMBERNUM, CARDSEQ )
VALUES (SEQ_TALK.NEXTVAL, '안녕하신가?', SYSDATE, 101, 5002);

INSERT INTO TALK (TALKSEQ, TALKCONTENT, TALKDATE, MEMBERNUM, CARDSEQ )
VALUES (SEQ_TALK.NEXTVAL, '안녕하신가?', SYSDATE, 101, 5002);

INSERT INTO TALK (TALKSEQ, TALKCONTENT, TALKDATE, MEMBERNUM, CARDSEQ )
VALUES (SEQ_TALK.NEXTVAL, '안녕하신가?', SYSDATE, 101, 5003);


SELECT * FROM TALK;